language: haskell

env:
  - 'UBUNTU_RELEASE=saucy GHCVER=7.8.3 CABALVER=1.20'
  - 'UBUNTU_RELEASE=trusty GHCVER=7.8.3 CABALVER=1.20'

before_install:
  - 'sudo apt-get install gearman-server'
  - sudo su -c 'echo "ENABLED=\"true\"" >> /etc/default/gearman-server'
  - sudo gearmand -p 4730 -d

  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_RELEASE} main universe"
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - sudo apt-get remove libzmq1
  - wget http://download.zeromq.org/zeromq-4.0.4.tar.gz
  - tar -xf zeromq-4.0.4.tar.gz
  - cd zeromq-4.0.4
  - ./configure
  - make
  - sudo make install
  - sudo su -c "echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf"
  - sudo ldconfig
  - cd ..

install:
  - 'cabal update'
  - 'mkdir deps'
  - 'cd deps'
  - 'git clone https://github.com/anchor/vaultaire-common'
  - 'git clone https://github.com/anchor/marquise'
  - 'git clone https://github.com/anchor/nagios-perfdata'
  - 'git clone https://github.com/anchor/gearman-haskell'
  - 'cd gearman-haskell'
  - 'git checkout 5a05bb9c540aecca456ca329bc5cd951d40e8418'
  - 'cd ../..'
  - 'cabal sandbox init'
  - 'cabal sandbox add-source ./deps/vaultaire-common'
  - 'cabal sandbox add-source ./deps/marquise'
  - 'cabal sandbox add-source ./deps/nagios-perfdata'
  - 'cabal sandbox add-source ./deps/gearman-haskell'
  - 'cabal install --only-dependencies --enable-tests --enable-benchmarks'

script:
  - 'cabal configure'
  - 'cabal build'
  - 'cabal test'
  - 'cabal sdist'
