language: haskell

env:
  - 'UBUNTU_RELEASE=saucy'
  - 'UBUNTU_RELEASE=trusty'

before_install:
  - 'sudo apt-get install cabal-install ghc happy'
  - 'sudo apt-get install gearman-server'
  - sudo su -c 'echo "ENABLED=\"true\"" >> /etc/default/gearman-server'
  - sudo gearmand -p 4730 -d

install:
  - 'cabal update'
  - 'mkdir deps'
  - 'cd deps'
  - 'git clone https://github.com/anchor/vaultaire-common'
  - 'git clone https://github.com/anchor/marquise'
  - 'git clone https://github.com/anchor/nagios-perfdata'
  - 'git clone https://github.com/anchor/gearman-haskell'
  - 'cd ..'
  - 'cabal sandbox init'
  - 'cabal sandbox add-source ./deps/vaultaire-common'
  - 'cabal sandbox add-source ./deps/marquise'
  - 'cabal sandbox add-source ./deps/nagios-perfdata'
  - 'cabal sandbox add-source ./deps/gearman-haskell'
  - 'cabal install --only-dependencies --enable-tests --enable-benchmarks'

script:
  - 'cabal configure'
  - 'cabal build'
  - 'cabal test'
  - 'cabal sdist'
